import { Playfair_Display, Raleway } from 'next/font/google'

import './globals.css'
import { getImageSize } from 'next/dist/server/image-optimizer'
const raleway_init = Raleway({
  subsets: ['latin'],
  weight: ['100', '300', '400'],
  variable: '--font-raleway',
})
const playfair_display_init = Playfair_Display({
  subsets: ['latin'],
  weight: '600',
  variable: '--font-playfair_display',
})

export const metadata = {
  title: "Ali's Portfolio",
  // description: 'Generated by create next app',
  //
  icons: {
    icon: '/portfolio3.png',

    // You can specify different sizes or types here
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${raleway_init.variable} ${playfair_display_init.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
